### ISSUE TITLE
The label is inconsistent with the real

### ISSUE THREAD

**Issue by iscyy** [ICVGIP-Challenge/SpeciesDetection-21#1]
The organizer, hi, may I ask if the files generated using yolov5 seem to be inconsistent with the real wild animals, why is this?<img width="418" alt="截屏2021-12-09 下午10 36 52" src="https://user-images.githubusercontent.com/24501320/145416638-97a5c701-66b7-439c-aad0-bf8d2421f533.png">

**Comment by yugpsyfer** [comment]
Hey @Him-wen, there are some empty images (with no animal) as well in the dataset, if this does not answer your question could you please elaborate a bit more. 

Thanks

**Comment by Him-wen** [comment]
> 嘿@Him-wen，数据集中也有一些空图像（没有动物），如果这不能回答您的问题，请您详细说明一下。
> 
> 谢谢

Hello, as shown in the figure above, in addition to category 0, I refer to categories 1-19, just like 10, 8, 1 and other obvious wild animals use code to visualize the mark error (no wild animals are marked). I printed 20 pictures in the run folder saved by the running code of YOLOv5. All of them were marked incorrectly. I studied for two days. The YOLOv5 code is original, probably not a problem with the code. I suspect that the data set is marked incorrectly. Can you answer it? Thank you, if it is convenient, you can export the TXT format label and use YOLOv5 to check whether the visual labeling is wrong, The following figure provides several visualization pictures enhanced by YOLOv5 data
From the folder ../Baselines/YOLOv5/run/train/train_batch(0-3).jpg
<img width="418" alt="截屏2021-12-09 下午10 36 52" src="https://user-images.githubusercontent.com/24501320/145567334-7ea614f2-153a-42b9-973c-9b478f028432.png">
From the folder ../Baselines/YOLOv5/run/train/train_batch(0-3).jpg
![train_batch0](https://user-images.githubusercontent.com/24501320/145567474-86e064ba-abfe-40e2-a115-62ff2dfd9648.jpeg)
![train_batch2](https://user-images.githubusercontent.com/24501320/145567634-61fff632-631d-4481-a195-9720dd68a4d4.jpeg)

**Comment by Him-wen** [comment]
Except for category 0, the other categories 1-19 are all marked correctly

**Comment by Him-wen** [comment]
@yugpsyfer I am very confused about this question. Is the data set correctly labeled?

**Comment by yugpsyfer** [comment]
@Him-wen YOLO, in a given frame, tries to detect as many objects as possible, it seems that this is happening in your case, the empty (0th) label is being detected for empty spaces in the images where the object's label is not 0.

PS - The images are mapped correctly.

**Comment by Him-wen** [comment]
@yugpsyfer  hi, I still have some doubts. I may not understand what you mean. This is a real box labeling, not a predicted box. Many objects whose category is not 0 are basically not labeled successfully. I don't understand it. Can you explain why? Thank you for your answers! Such as the following picture.
![截屏2021-12-10 下午9 21 45](https://user-images.githubusercontent.com/24501320/145580484-2f34b818-c8d2-4f0d-aef2-fb0e167)
![截屏2021-12-10 下午9 22 23](https://user-images.githubusercontent.com/24501320/145580594-d0ece729-5da8-4555-b909-8ef41bde100b.png)
e2943.png)
![截屏2021-12-10 下午9 22 18](https://user-images.githubusercontent.com/24501320/145580606-10b9ebd2-aa36-436c-a863-5de428b904a1.png)
![截屏2021-12-10 下午9 22 10](https://user-images.githubusercontent.com/24501320/145580615-111e581f-7b9c-42af-a4d4-25bfca
![截屏2021-12-10 下午9 22 04](https://user-images.githubusercontent.com/24501320/145580622-82724456-3df7-492f-9800-560f351baadd.png)
3de812.png)

**Comment by Him-wen** [comment]
‘The images are mapped correctly.’ , I don't understand this sentence.

**Comment by yugpsyfer** [comment]
@Him-wen The BBoxes above are actually detecting something which is not there and can be said that they have falsely determined that an object of certain label is present in the image which is not actually there. And by the sentence that **The images are mapped correctly** I mean that the images have correct labels, there is no label mismatch in the dataset.

**Comment by Him-wen** [comment]
Thank you for your patience, but this is a training set, why is the label not matched? I have observed that the pictures printed in other data sets are basically all matched successfully. For example, according to your opinion, is this a normal situation? I still can’t understand this situation, if I disturb you, I apologize
<img width="654" alt="test" src="https://user-images.githubusercontent.com/24501320/145593973-6de5b20f-4510-4edc-8215-3093b8a920dd.png">

**Comment by yugpsyfer** [comment]
If the images that you have output in a folder are YOLO's detection then it is normal for some of them to be misclassified. But if you check the train.json and then draw the bboxes according to it on any image you will observe that the bboxes are correct with respect to that image and the label is also correct. But here you are using a classifier to determine whether an object present inside an image is of a certain label, here during detection there can be misclassifications. For example in the above image that you have posted all the bboxes are probably around the required objects, but there can be bboxes that may surround no object at all or wrong object and hence may misclassify some object to some other label.

**Comment by Him-wen** [comment]
@yugpsyfer thanks

**Comment by yugpsyfer** [comment]
@Him-wen Marking this as resolved.
