### ISSUE TITLE
Case mismatch in label conversion

### ISSUE THREAD

**Issue by DensenDavis** [ICVGIP-Challenge/SpeciesDetection-21#2]
In Baselines/YOLOv5/create_labels.py train_json_path and valid_json_path have lowercase keyword "dataset" but is sentence cased as "Dataset" in the actual physical path.

**Comment by iscyy** [comment]
> 在 Baselines/YOLOv5/create_labels.py 中，train_json_path 和 valid_json_path 有小写的关键字“dataset”，但在实际物理路径中的句子大小写为“Dataset”。

hi hello, is your label symmetrical to the object one by one? I feel that all the annotated images are problematic. Have you encountered this situation?
<img width="418" alt="截屏2021-12-09 下午10 36 52" src="https://user-images.githubusercontent.com/24501320/145550646-66c5fcec-d7ed-489c-858f-30137f6c6b0b.png">

**Comment by yugpsyfer** [comment]
@DensenDavis I do not get what the issue is, could you perhaps post some screenshots of the same.
