### ISSUE TITLE
about create_yolo.py

### ISSUE THREAD

**Issue by iscyy** [ICVGIP-Challenge/SpeciesDetection-21#4]
Hello, is there any problem with the create_labels.py provided in YOLOv5? I tested it and the conversion failed
![](https://user-images.githubusercontent.com/24501320/145702287-40fecc3d-69af-4f96-ae67-ec163ef1ec3c.png)

**Comment by yugpsyfer** [comment]
@Him-wen can you please provide me with more details of the same? Like image id and is this from validation or train?

**Comment by Him-wen** [comment]
hi, @yugpsyfer  The training image is shown here. I tried the image in json format. The annotation is no problem, but after the conversion of create_yolo.py, the annotation is wrong. Can you reproduce it there? 
These details come from the real annotations of the training images, not the verification or test images
This is from the official yolov5 document
<img width="960" alt="x" src="https://user-images.githubusercontent.com/24501320/145710668-1c21957f-a9c4-4af3-92bf-c7e6059c9f75.png">
This is a visualization of my training image
<img width="948" alt="x" src="https://user-images.githubusercontent.com/24501320/145710733-40ac9b96-a2f6-4bbc-87b5-12aab38250c1.png">
<img width="931" alt="x" src="https://user-images.githubusercontent.com/24501320/145710737-105e36a1-1f99-40b3-881c-89b1ae42b8a5.png">
The problem should be the conversion of json to txt format, but I did not convert it extra

**Comment by yugpsyfer** [comment]
@Him-wen can you also provide the txt files for above images?

**Comment by Him-wen** [comment]
hi, @yugpsyfer This is the txt folder compressed package I converted, you can download it and take a look.
[Click this link to have a rar compressed package](https://github.com/Him-wen/Object-Detection-Tools)(train_txt, validation_txt)

**Comment by yugpsyfer** [comment]
@Him-wen Can you also tell how did you visualize did you directly visualize them? the text files?

**Comment by Him-wen** [comment]
@yugpsyfer Using the YOLOv5 framework, without data enhancement, each printed picture with annotations

**Comment by yugpsyfer** [comment]
@Him-wen Please also point me towards that code

**Comment by Him-wen** [comment]
1.Click on this link and follow the method here (after the label has been converted, do not perform the first step(Including the second, third, and fourth steps)
https://github.com/ICVGIP-Challenge/SpeciesDetection-21/tree/main/Baselines/YOLOv5  
2.Training command：
python train.py --img 640 --cfg ./models/yolov5s.yaml --batch 16 --epochs 10 --data ./data/icvgip.yaml --name icvgip
3.When starting training, The visualized picture can be viewed at ./run/train/train_batch.jpg

**Comment by Him-wen** [comment]
Regarding the code, I use the official yolov5

**Comment by yugpsyfer** [comment]
@Him-wen Are there are a lot of images that are exhibiting this issue?

**Comment by Him-wen** [comment]
@yugpsyfer Except for the background image of category 0, other labeled images are basically marked with deviations
For example
<img width="931" alt="" src="https://user-images.githubusercontent.com/24501320/145720352-178b8b7d-3e56-444f-86d2-19efcbb20ba9.png">

**Comment by Him-wen** [comment]
@yugpsyfer Have you noticed any problems?

**Comment by yugpsyfer** [comment]
@Him-wen The images that you have provided us are they after training, or before training?

**Comment by Him-wen** [comment]
@yugpsyfer Is the real label marked before training

**Comment by Him-wen** [comment]
@yugpsyfer Can you run the yolov5 code over there? And check the recorded runs/train/train_batch0.jpg... image

**Comment by Him-wen** [comment]
Is this competition very few people participated in? This label conversion should be wrong, but it seems that no one else has responded. I re-written a .py file about the conversion of coco format to yolo format.
